/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as RedefinirSenhaRouteImport } from './routes/redefinir-senha'
import { Route as AuthenticatedPainelRouteImport } from './routes/_authenticated/painel'
import { Route as AuthenticatedPainelIndexRouteImport } from './routes/_authenticated/painel.index'
import { Route as AuthenticatedPainelAdminRouteImport } from './routes/_authenticated/painel.admin'
import { Route as AuthenticatedPainelCertificadosRouteImport } from './routes/_authenticated/painel.certificados'
import { Route as AuthenticatedPainelContaRouteImport } from './routes/_authenticated/painel.conta'
import { Route as AuthenticatedPainelDocumentosRouteImport } from './routes/_authenticated/painel.documentos'
import { Route as AuthenticatedPainelMarcasRouteImport } from './routes/_authenticated/painel.marcas'
import { Route as AuthenticatedPainelSuporteRouteImport } from './routes/_authenticated/painel.suporte'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const RedefinirSenhaRoute = RedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPainelRoute = AuthenticatedPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPainelIndexRoute =
  AuthenticatedPainelIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const AuthenticatedPainelAdminRoute =
  AuthenticatedPainelAdminRouteImport.update({
    id: '/admin',
    path: '/admin',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const AuthenticatedPainelCertificadosRoute =
  AuthenticatedPainelCertificadosRouteImport.update({
    id: '/certificados',
    path: '/certificados',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const AuthenticatedPainelContaRoute =
  AuthenticatedPainelContaRouteImport.update({
    id: '/conta',
    path: '/conta',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const AuthenticatedPainelDocumentosRoute =
  AuthenticatedPainelDocumentosRouteImport.update({
    id: '/documentos',
    path: '/documentos',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const AuthenticatedPainelMarcasRoute =
  AuthenticatedPainelMarcasRouteImport.update({
    id: '/marcas',
    path: '/marcas',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const AuthenticatedPainelSuporteRoute =
  AuthenticatedPainelSuporteRouteImport.update({
    id: '/suporte',
    path: '/suporte',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/painel': typeof AuthenticatedPainelRouteWithChildren
  '/painel/admin': typeof AuthenticatedPainelAdminRoute
  '/painel/certificados': typeof AuthenticatedPainelCertificadosRoute
  '/painel/conta': typeof AuthenticatedPainelContaRoute
  '/painel/documentos': typeof AuthenticatedPainelDocumentosRoute
  '/painel/marcas': typeof AuthenticatedPainelMarcasRoute
  '/painel/suporte': typeof AuthenticatedPainelSuporteRoute
  '/painel/': typeof AuthenticatedPainelIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/painel/admin': typeof AuthenticatedPainelAdminRoute
  '/painel/certificados': typeof AuthenticatedPainelCertificadosRoute
  '/painel/conta': typeof AuthenticatedPainelContaRoute
  '/painel/documentos': typeof AuthenticatedPainelDocumentosRoute
  '/painel/marcas': typeof AuthenticatedPainelMarcasRoute
  '/painel/suporte': typeof AuthenticatedPainelSuporteRoute
  '/painel': typeof AuthenticatedPainelIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/_authenticated/painel': typeof AuthenticatedPainelRouteWithChildren
  '/_authenticated/painel/admin': typeof AuthenticatedPainelAdminRoute
  '/_authenticated/painel/certificados': typeof AuthenticatedPainelCertificadosRoute
  '/_authenticated/painel/conta': typeof AuthenticatedPainelContaRoute
  '/_authenticated/painel/documentos': typeof AuthenticatedPainelDocumentosRoute
  '/_authenticated/painel/marcas': typeof AuthenticatedPainelMarcasRoute
  '/_authenticated/painel/suporte': typeof AuthenticatedPainelSuporteRoute
  '/_authenticated/painel/': typeof AuthenticatedPainelIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/redefinir-senha'
    | '/painel'
    | '/painel/admin'
    | '/painel/certificados'
    | '/painel/conta'
    | '/painel/documentos'
    | '/painel/marcas'
    | '/painel/suporte'
    | '/painel/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/redefinir-senha'
    | '/painel/admin'
    | '/painel/certificados'
    | '/painel/conta'
    | '/painel/documentos'
    | '/painel/marcas'
    | '/painel/suporte'
    | '/painel'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/redefinir-senha'
    | '/_authenticated/painel'
    | '/_authenticated/painel/admin'
    | '/_authenticated/painel/certificados'
    | '/_authenticated/painel/conta'
    | '/_authenticated/painel/documentos'
    | '/_authenticated/painel/marcas'
    | '/_authenticated/painel/suporte'
    | '/_authenticated/painel/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  RedefinirSenhaRoute: typeof RedefinirSenhaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redefinir-senha': {
      id: '/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof RedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/painel': {
      id: '/_authenticated/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AuthenticatedPainelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel/': {
      id: '/_authenticated/painel/'
      path: '/'
      fullPath: '/painel/'
      preLoaderRoute: typeof AuthenticatedPainelIndexRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/painel/admin': {
      id: '/_authenticated/painel/admin'
      path: '/admin'
      fullPath: '/painel/admin'
      preLoaderRoute: typeof AuthenticatedPainelAdminRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/painel/certificados': {
      id: '/_authenticated/painel/certificados'
      path: '/certificados'
      fullPath: '/painel/certificados'
      preLoaderRoute: typeof AuthenticatedPainelCertificadosRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/painel/conta': {
      id: '/_authenticated/painel/conta'
      path: '/conta'
      fullPath: '/painel/conta'
      preLoaderRoute: typeof AuthenticatedPainelContaRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/painel/documentos': {
      id: '/_authenticated/painel/documentos'
      path: '/documentos'
      fullPath: '/painel/documentos'
      preLoaderRoute: typeof AuthenticatedPainelDocumentosRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/painel/marcas': {
      id: '/_authenticated/painel/marcas'
      path: '/marcas'
      fullPath: '/painel/marcas'
      preLoaderRoute: typeof AuthenticatedPainelMarcasRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/painel/suporte': {
      id: '/_authenticated/painel/suporte'
      path: '/suporte'
      fullPath: '/painel/suporte'
      preLoaderRoute: typeof AuthenticatedPainelSuporteRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
  }
}

interface AuthenticatedPainelRouteChildren {
  AuthenticatedPainelAdminRoute: typeof AuthenticatedPainelAdminRoute
  AuthenticatedPainelCertificadosRoute: typeof AuthenticatedPainelCertificadosRoute
  AuthenticatedPainelContaRoute: typeof AuthenticatedPainelContaRoute
  AuthenticatedPainelDocumentosRoute: typeof AuthenticatedPainelDocumentosRoute
  AuthenticatedPainelMarcasRoute: typeof AuthenticatedPainelMarcasRoute
  AuthenticatedPainelSuporteRoute: typeof AuthenticatedPainelSuporteRoute
  AuthenticatedPainelIndexRoute: typeof AuthenticatedPainelIndexRoute
}

const AuthenticatedPainelRouteChildren: AuthenticatedPainelRouteChildren = {
  AuthenticatedPainelAdminRoute: AuthenticatedPainelAdminRoute,
  AuthenticatedPainelCertificadosRoute: AuthenticatedPainelCertificadosRoute,
  AuthenticatedPainelContaRoute: AuthenticatedPainelContaRoute,
  AuthenticatedPainelDocumentosRoute: AuthenticatedPainelDocumentosRoute,
  AuthenticatedPainelMarcasRoute: AuthenticatedPainelMarcasRoute,
  AuthenticatedPainelSuporteRoute: AuthenticatedPainelSuporteRoute,
  AuthenticatedPainelIndexRoute: AuthenticatedPainelIndexRoute,
}

const AuthenticatedPainelRouteWithChildren =
  AuthenticatedPainelRoute._addFileChildren(AuthenticatedPainelRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedPainelRoute: typeof AuthenticatedPainelRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedPainelRoute: AuthenticatedPainelRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  RedefinirSenhaRoute: RedefinirSenhaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
